// votacao/src/Components/Results.svelte
<script>
    import { onMount } from 'svelte';

    export let options = [];
    let results = [];
    let totalVotes = 0;

    onMount(async () => {
        loadResults();
	});

    const loadResults = () => {
        countVotes();
        options.forEach((option, index) => {
            results = [...results, renderResult(option, index)]
        })
    }

    const renderResult = (option, index) => {
        return `${index + 1}. ${option.text} - ${option.count} votes (${calculatePercentage(option.count)}%)`
    }

    const calculatePercentage = (optionCount) => {
        return Math.round((optionCount / totalVotes) * 100)
    }

    const countVotes = () => {
        options.forEach(option => {
            totalVotes += option.count;
        });
    }

</script>

{#each results as result}
<p>{result}</p>
{/each}

// votacao/src/app/results/results.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-results',
  templateUrl: './results.component.html',
  styleUrls: ['./results.component.css']
})
export class ResultsComponent implements OnInit {

  @Input() 
  options : any[];

  results : string[];

  constructor() { 
    this.results = []
    this.options = [];

  }

  ngOnInit(): void {
    this.handleOptions();
  }

  handleOptions = (): void => {
    let totalVotes = 0;
    this.options.forEach((option) => {
      totalVotes += option.count;
    })

    this.options.map((option, index) => {
      this.results.push(this.getSingleResultText(totalVotes, option, index))
    })
  }

  getSingleResultText = (totalCount:number, option:any, index: number) : string=> {
    return `${index + 1} - ${option.text} - ${option.count} votes (${this.calculatePercentage(option.count, totalCount)}%)`;
  }

  calculatePercentage = (optionCount: number, totalCount: number): number => {
    return Math.round((optionCount / totalCount) * 100);
  }

}

<p>resultados</p>
<p *ngFor="let result of results">{{result}}</p>
