// votacao/src/Components/Booth.svelte
<script>
    import { formOptions } from '../stores/formData';
    import { votingState } from '../stores/states';

    let options;

    formOptions.subscribe(data => {
        options = data;
    })

    const onVote = (data) => {
        countVote(data);

        votingState.update(currentOptions => {
            return "closed";
        })
    }

    const countVote = (vote) => {
        let localOptions = [...options];
        localOptions.forEach(option => {
            if(option.text === vote){
                option.count++;
            }
        })
        formOptions.update(() => {
            return localOptions;
        })
    }

</script>

{#each options as option}
<button on:click={()=>onVote(option.text)}>{option.text}</button>
{/each}

// votacao/src/app/booth/booth.component.ts
import { Component, OnInit } from '@angular/core';
import { DataServiceService } from '../data-service.service';

@Component({
  selector: 'app-booth',
  templateUrl: './booth.component.html',
  styleUrls: ['./booth.component.css']
})
export class BoothComponent implements OnInit {

  options:{ text: string; count: number; }[] = [];

  constructor() {
    this.options = DataServiceService.formOptions;
  }

  ngOnInit(): void {
   
  }

  onClick = (selectedOption: string) => {
    let localOptions = [...this.options];
    localOptions.forEach((option) => {
      if(option.text === selectedOption){
        option.count++;
      }
    })
    DataServiceService.formOptions = localOptions;
    DataServiceService.votingStatus = "closed";
  }
}

<p>booth</p>
<button *ngFor="let option of options" (click)="onClick(option.text)">{{option.text}}</button>
