// votacao/src/Components/Booth.svelte
<script>
    import {createEventDispatcher} from 'svelte';
    import { formOptions } from '../stores/formData';
    const dispatch = createEventDispatcher();

    export let options = []

    let localOptions;

    formOptions.subscribe(data => {
        localOptions = data;
    })

</script>

{#each options as option}
<button on:click={()=>dispatch('vote', option.text)}>{option.text}</button>
{/each}

// votacao/src/components/Booth.vue
<template>
    <div>
        <button v-for="option in options" :key="option.text" v-on:click="vote(option.text)">
            {{option.text}}
        </button>
    </div> 
</template>

<script>

    import useStore from '../store';

    export default {
        name: 'booth',
        data(){
            return {
                options: []
            }
        }, 
        methods: {
            vote(option){
                this.$emit("vote", option);
            },
            
        }, mounted(){
            const store = useStore();
            this.options = store.formOptions;
        }
    }
</script>
