// votacao/src/app/voting-card/voting-card.component.ts
import { ThrowStmt } from '@angular/compiler';
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-voting-card',
  templateUrl: './voting-card.component.html',
  styleUrls: ['./voting-card.component.css']
})
export class VotingCardComponent implements OnInit {

  @Input() 
  title = "";

  @Input() 
  state = "";

  @Input() 
  options : any[];

  constructor() { 
    this.options = [];
  }

  ngOnInit(): void {
  }

  onVote(selectedOption: string): void {
    console.log("foi votado em...");
    console.log(selectedOption);
    this.options.forEach((option) => {
      if(option.text === selectedOption){
        option.count++;
      }
    })
    this.state = "closed";
  }

}

<p>{{title}}</p>
<app-results [options]="options" *ngIf="state !== 'open'"></app-results>
<app-booth [options]="options" *ngIf="state === 'open'" (vote)="onVote($event)"></app-booth>

// votacao/src/components/VotingCard.vue
<template>
    <div>
        <h3>{{this.title}}</h3>
        <booth v-if="localState==='open'" :options="localOptions" v-on:vote="handleVote($event)"/>
        <results v-if="localState!=='open'" :options="localOptions"/>
    </div>
</template>

<script>
    import Results from './Results.vue';
    import Booth from './Booth.vue';

    export default {
        name: 'voting-card',
        props: {
            options: [],
            state: "",
            title: ""
        },
        components: {
            Results,
            Booth
        },
        data(){
            return {
               localState: this.state,
               localOptions: this.options
            }
        }, 
        methods: {
            handleVote(option){
                this.localState = "closed"
                this.localOptions.forEach(op => {
                    if(op.text === option){
                        op.count++;
                    }
                });
            }
        },
        watch: {
            state: function(){
                this.localState = this.state;
            },
            options: function(){
                this.localOptions = this.options;
            }
        }
    }
</script>
