// votacao/src/components/VotingCard.vue
<template>
    <div>
        <h3>{{this.title}}</h3>
        <booth v-if="localState==='open'" :options="localOptions" v-on:vote="handleVote($event)"/>
        <results v-if="localState!=='open'" :options="localOptions"/>
    </div>
</template>

<script>
    import Results from './Results.vue';
    import Booth from './Booth.vue';

    export default {
        name: 'voting-card',
        props: {
            options: [],
            state: "",
            title: ""
        },
        components: {
            Results,
            Booth
        },
        data(){
            return {
               localState: this.state,
               localOptions: this.options
            }
        }, 
        methods: {
            handleVote(option){
                this.localState = "closed"
                this.localOptions.forEach(op => {
                    if(op.text === option){
                        op.count++;
                    }
                });
            }
        },
        watch: {
            state: function(){
                this.localState = this.state;
            },
            options: function(){
                this.localOptions = this.options;
            }
        }
    }
</script>

// votacao/src/Components/VotingCard.svelte
<script>
    import Results from './Results.svelte';
    import Booth from './Booth.svelte';

    export let title = "";
    export let options = [];
    export let state = "";

    const onVote = (data) => {
        countVote(data.detail);
        state = "closed"
    }

    const countVote = (vote) => {
        let localOptions = [...options];
        localOptions.forEach(option => {
            if(option.text === vote){
                option.count++;
            }
        })
        options = localOptions;
    }

</script>

<h3>{title}</h3>
{#if state === "open"}
<Booth options={options} on:vote={onVote}/>
{/if}
{#if state !== "open"}
<Results options={options}/>
{/if}
